site_name: KinGenie
use_directory_urls: false
theme:
  name: "material"
  font: false
nav:
  - Documentation: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - Background: explanation.md

plugins:
  - mkdocstrings